### ISSUE TITLE
Troubleshooting form submission

### ISSUE THREAD

**Issue by danaskallman** [mecachisenros/caldera-forms-civicrm#1]
I did a quick test in creating a form that has an activity attached and attempted to submit more than once. On the second time it did not work. The idea/use case would be creating a few forms for a team to add items like phone calls or meetings without coming into CiviCRM. Or if using the Civivolunteer forms could be created to log time for example.

**Comment by mecachisenros** [comment]
@danaskallman how did you configured the form? More specifically the Civi processors, the most important thing to be aware of is the order they are added, you want to have a **Contact processor** as the **first processor** and then link the rest of the entities/processors like activities, groups, tags, (you can add as many processors as you need, ie. multiple Group processor that are only used if a certain field is selected or the value of a field is X) to the Contact processor via the **Contact Link**.

I will update the readme file with a short tutorial.

**Comment by danaskallman** [comment]
ok so my latest test, with 10 contact processors all first provides the following output with debug enabled. After that I've noted primary contact phone and address processors, then relationships and last other contact phone processors. 

Notice: Undefined index: dedupe_rule in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 577

Notice: Undefined index: source in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 577

Notice: Undefined index: custom_12 in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 577

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 569

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 575

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 569

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 575

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 569

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 575

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 569

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 575

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 569

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 575

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 569

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 575

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 569

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 575

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 569

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 575

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 569

Notice: Undefined variable: civi_contact in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 575

Notice: Undefined variable: civi_contact_address in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 602

Notice: Undefined variable: civi_contact_phone in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 658

Notice: Undefined variable: civi_contact_phone in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 658

Notice: Undefined variable: civi_contact_email in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 630

Notice: Undefined variable: civi_contact_phone in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 658

Notice: Undefined variable: civi_contact_phone in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 658

Notice: Undefined variable: civi_contact_phone in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 658

Notice: Undefined variable: civi_contact_phone in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php on line 658

Notice: Undefined index: conditions in /home/point/public_html/wp-content/plugins/caldera-forms/classes/core.php on line 1565

Notice: Undefined index: type in /home/point/public_html/wp-content/plugins/caldera-forms/classes/core.php on line 4899

Notice: Undefined index: slug in /home/point/public_html/wp-content/plugins/caldera-forms/classes/core.php on line 4900

Notice: Undefined index: conditions in /home/point/public_html/wp-content/plugins/caldera-forms/classes/core.php on line 1565

Notice: Undefined index: type in /home/point/public_html/wp-content/plugins/caldera-forms/classes/core.php on line 4899

Notice: Undefined index: slug in /home/point/public_html/wp-content/plugins/caldera-forms/classes/core.php on line 4900

I'll go through the form again, since it's quite complex I may have missed some settings. But wanted to share this as an update.

**Comment by mecachisenros** [comment]
@danaskallman the PHP notices should be fixed now, although that shouldn't prevent the form from submitting.
A thing to have in mind is that if you are submitting the form with empty fields values the processors will still be processed, and therefore it will fail, ie creating an activity with empty parameters, if that's the case you could use a Conditional rule for the processor to be used only if the relevant field is not empty, like image below.
![capture](https://cloud.githubusercontent.com/assets/3038096/17937769/2cb94cb0-6a1b-11e6-9041-266bdae0d8f7.PNG)

**Comment by danaskallman** [comment]
@mecachisenros I had not reviewed the conditions within each processor, thanks for sharing that. 

Over the past week I deployed a site with this plugin, form seen here: https://dawn.coop/dawn-technical-assistance-request/

It took me quite a bit of trial and error to get the form to work. If I created all fields in Caldera and then Civi it didn't always work, I am guessing since the field value may not have matched. What I ended up doing was adding a field at a time and submitting the form to test that it work and then adding another field and testing until the form was complete and all fields submitted got added to an activity with the correct contact details too. So now it's working like a charm, which is very exciting :)

I'll probably do the same with the other form noted in the previous issue to determine what field(s) the issue may be the culprit and what changes may needed in field to process. 

I am not sure how this affects this issue, but I thought I'd post an update too.

**Comment by mecachisenros** [comment]
@danaskallman Thanks for reporting.
Now I understand a bit more. I just noticed the heavy use of checkboxes/radio fields in the form you mentioned, I can imagine how much time consuming that must be (ie manually inputting all the options/values into the form) and how easy is to make a mistake. But I have good news, now you can achieve this automatically/dynamically, you have two options, either use the 'autopopulate' feature or the 'bulk insert/presets' for any checkbox/radio/dropdown/select2/etc field, you'll see all your Civi custom options fields with a type of Select, Radio, CheckBox, Multi-Select or AdvMulti-Select. For now it supports custom fields that extend the Activity and Contact entities (including any contact type).
Post back any updates you have or any suggestions.

**Comment by danaskallman** [comment]
@mecachisenros nice, this is way cool! I only did a quick test so far, will review in more detail and post more updates if I find anything. 

As of now I'd opt for the 'bulk insert/presets' since the notification summary would have all fields displayed. When I used the Civi State field it appears as a number in the notification.

**Comment by mecachisenros** [comment]
@danaskallman you're correct, that's how the "summary" tag works, for all **select fields** it will always output the value (in the Country/State case is the country/state id from Civi) instead of the label, but I believe that doesn't happen with checkbox/radio fields, so as long the field is a checkbox/radio it shouldn't matter if you use 'autopopulate' or 'bulk insert', it only happens with select/dropdown fields.

If you want to output the label of a select field in the notification email you could use the magic tag like `%slug:label%` ie say the slug of the State field is `state_province` then in the notification you could put `%state_province:label%`

Note aside regarding emails. 
I was thinking to add a **Send Civi Email** processor for those who have installed the Civi email API, I'm a big fan of Civi tokens and smarty in emails and I think it would be a great addition to be able to send email to the contact that submitted the form directly from Civi using Civi's message templates. any thoughts on that?

**Comment by danaskallman** [comment]
@mecachisenros let me try that re: magic tag.

Re: Send Civi Email, I am not sure I fully understand. But if I am following you are saying instead of using the autoresponses in Caldera that we use Civi templates for that? And that template would be selected from the available ones? 

Maybe we start a new issue for this.

**Comment by danaskallman** [comment]
Ok, so the saga continues...I am working on the form that is asking for 10 contacts and 28 processors. I've gone through and made sure field values match up, added conditionals of when to use a contact processor and the errors I am getting are these: 

~~~
Notice: Undefined index: contact_id_3 in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/processors/relationship/class-relationship-processor.php on line 71

Notice: Undefined index: contact_id_4 in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/processors/relationship/class-relationship-processor.php on line 71

Notice: Undefined index: contact_id_4 in /home/point/public_html/wp-content/plugins/caldera-forms-civicrm/processors/relationship/class-relationship-processor.php on line 82

Fatal error: Uncaught CiviCRM_API3_Exception: [mandatory_missing: Mandatory key(s) missing from params array: contact_id_b thrown in /home/point/public_html/wp-content/plugins/civicrm/civicrm/api/api.php on line 45
~~~

I am using the same relationship like Parent of or Emergency Contact of more than once, since the forms allows for up to 2 parents and 2 emergency contacts to be added. Thoughts on what else it could be?

**Comment by mecachisenros** [comment]
@danaskallman it looks like Contact 3 and Contact 4 are not being processed/set so the relationship then fails, does that make sense?

**Comment by danaskallman** [comment]
@mecachisenros Ah, I see. Those contacts are not always used and I've set to use only if condition is met. Do I have to add the Use conditions in the relationship processor too?

**Comment by mecachisenros** [comment]
Yes, that is correct @danaskallman, you'll have to add a condition to the relationship processor so it's processed only when Contact 3 **and** Contact 4 are set

**Comment by danaskallman** [comment]
Hmmm, well that damn long form has me stumpped. Not those errors are gone but don't submit. I'll go through the thing again and see if I missed anything. It will be easier with #14 since it's one longer processor and one condition for all. Though not sure about the relationship part yet.

**Comment by christianwach** [comment]
> those errors are gone but don't submit

@danaskallman I found that when I used a form with an email field that has the slug 'email', that the form silently fails when the honeypot is active in the form settings, because the honeypot sometimes uses a hidden field with that slug to catch spammers. See https://github.com/mecachisenros/caldera-forms-civicrm/pull/19#issuecomment-253765978 for details.

**Comment by danaskallman** [comment]
That's good to know, thanks @christianwach

**Comment by danaskallman** [comment]
Specific issues can be opened going forward, so will close this issue since it's more generic and maybe some issue covered through more docs and fixes since this issue was started.
