### ISSUE TITLE
Contact Custom fields don't display when returning to Edit a form processor

### ISSUE THREAD

**Issue by danaskallman** [mecachisenros/caldera-forms-civicrm#10]
I've noticed on a couple of sites now that when a custom field is for Individuals, no sub-contact type, when I go back and edit a form those custom fields are no longer listed in the processor. When I first added the processor it was there, but not after I come back to edit. Those custom fields that are for sub-contact type of an Individual do appear. Thoughts on why this may be?

**Comment by mecachisenros** [comment]
@danaskallman I think that should fix it

**Comment by danaskallman** [comment]
It worked in that the Custom Field shows up, but can only see the contact and details of the first processor. All other processors appear empty, with no settings/options just the Remove Processor option.

**Comment by danaskallman** [comment]
Adding console error messages. Let me know if there is more needed, not sure what part is the most informative.

~~~
content script runtime.onMessage:  update_shortcutscontent_script.js:91:2
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
TypeError: e is undefined
load-scripts.php:585:1538
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
TypeError: e is undefined
load-scripts.php:585:1538
content script runtime.onMessage:  tabupdatecontent_script.js:91:2
POST 
XHR 
https://.../wp-admin/admin-ajax.php [HTTP/1.1 200 OK 1050ms]
TypeError: e is undefined
~~~

**Comment by mecachisenros** [comment]
@danaskallman apologies about that, I missed an opening bracket d80832dfab357429dbaac73fcf073a3852635ce2

**Comment by danaskallman** [comment]
No worries @mecachisenros thanks, that did it!
