### ISSUE TITLE
case_id is not a valid integer in Activity Processor – Case was not created

### ISSUE THREAD

**Issue by agileware-fj** [mecachisenros/caldera-forms-civicrm#106]
**Describe the bug**

Activity processors linked up to a Case processor in an earlier step are failing to create the activities,  and an exception is thrown `case_id is not a valid Integer`.
This was originally filed as a handling bug, however on review the case is not created because of an incorrect configuration.
As such, refiling as a UX issue.

**To Reproduce**
1. Create a form that collects Name and Email for a Case and an Activity filed on it (email may not be necessary but we want to create a unique contact)
2. Add a Contact processor
3. Add a Case processor that creates a new case linked to the Contact in step 2
  a. Do **not** fill in the Case Subject
4. Add an Activity processor that files the Activity on the Case in step 3
5. Attempt to submit the form

**Expected behavior**
- A user friendly error message is shown in step 5 to indicate the case was not created; OR
- The Case processor configuration is marked as invalid during step 3 as a required field is missing

**Comment by agileware-fj** [comment]
Agileware ref SUP-8392

**Comment by mecachisenros** [comment]
@agileware-fj thanks for reporting, I'll have a look.

**Comment by mecachisenros** [comment]
@agileware-fj in step 3, you shouldn't be able to save the form if no Case Subject is provided (Case Subject **is** a required field), this is what I get if I try saving the form without a Case Subject.

![case_subject_required](https://user-images.githubusercontent.com/3038096/54718558-ae965500-4b52-11e9-88af-3f68487ec37c.png)

**Comment by mecachisenros** [comment]
I've added a error message to notify that the Activity has not been created.

![activity_error_message](https://user-images.githubusercontent.com/3038096/54720863-709c2f80-4b58-11e9-9f69-77778ec72746.png)

**Comment by agileware-fj** [comment]
@mecachisenros that's weird, as this is actually an error that came up on a production site where the case subject field was not filled in.  Caldera 1.8.2 and Caldera Forms CiviCRM 1.0.2, no patches.
We saved the form configuration multiple times, including alterations to the case processor, without running into any validation issues, before determining that the problem was the case subject was not filled in.

In terms of the error message, I think we actually need feedback when the *case* is not created / linked, because what was not obvious was *why* the case_id was not valid.

**Comment by mecachisenros** [comment]
@agileware-fj that's odd indeed, that field [is required ](https://github.com/mecachisenros/caldera-forms-civicrm/blob/master/processors/case/case_config.php#L80).

I misunderstood your point thinking about the Activity, but yes, the Case will fail if no Subject is provided.

I think this should do it:
![case_error](https://user-images.githubusercontent.com/3038096/54728795-da780180-4b77-11e9-9e00-a06b3f25beeb.png)

**Comment by agileware-fj** [comment]
Thanks, happy with that addition.
