### ISSUE TITLE
Auto Populate from custom field source won't include more than 25 options

### ISSUE THREAD

**Issue by kirk-circle** [mecachisenros/caldera-forms-civicrm#107]
**Description**
When a Dropdown Select field in Caldera Forms is set to Auto Populate from an Integer Select custom field in CiviCRM, the dropdown is only populated with 25 options. If the custom field has more than 25 options, then some will be missing.

**To Reproduce**
1. In CiviCRM, create an Integer Select custom field and add 26 options.
2. In Caldera Forms, create a Dropdown Select field and set it to Auto Populate from the CiviCRM custom field.
3. Save and Preview the Form.
4. Count the number of options in the Dropdown Select field.

**Expected behavior**
All of the CiviCRM custom field's options should be included in the dropdown in Caldera Forms.

**Environment**
- OS: Ubuntu 18.04
- WordPress 5.1.1
- CiviCRM 5.9.0
- Caldera Forms 1.8.2
- Caldera Forms CiviCRM 1.0.2

**Additional context**
It seems likely that Caldera Forms CiviCRM is fetching the options from CiviCRM using an API call without specifying the [limit option](https://docs.civicrm.org/dev/en/latest/api/options/#optionslimit). If so, this problem could be fixed easily by specifying a limit of 0 in the API call.

**Comment by mecachisenros** [comment]
@kirk-circle thanks for reporting, this is fixed via the referenced commit.

**Comment by kirk-circle** [comment]
Thank you very much. In future I will try to submit a PR if and when I raise an issue.
