### ISSUE TITLE
Processors UI

### ISSUE THREAD

**Issue by danaskallman** [mecachisenros/caldera-forms-civicrm#14]
I have been setting up a few forms and learning how to use Caldera forms in the process. And processors are where the integration points are created to 'sync' date into CiviCRM. Currently there are the following processors: 
- CiviCRM Contact
- CiviCRM Activity
- CiviCRM Relationship
- CiviCRM Tag
- CiviCRM Address
- CiviCRM Email
- CiviCRM Phone 
- CiviCRM Note

And there could be more, like Website/IM and then even more if we add ways to integrate contributions, memberships, events, surveys, petitions, etc. This can get unwieldy when using a lot of contacts. One form I'm working on that is asking for 10 contacts is using 28 processors. 

Are there ways to have less overall processors and have more options within a processor. Maybe using the CiviCRM Admin menu as guide, basically the CiviCRM Components. Those would be:
- Contacts
- Contributions
- Events
- Malings
- Membership
- Campaigns

Based on whatever components are enabled on that specific instance of CiviCRM. This is an initial thought to brainstorm. I'll outline in a bit more detail what the CiviCRM Contacts processor could maybe do based on what' in place now.

**Comment by danaskallman** [comment]
All the processors in place now revolve around the CiviCRM Contact. Could this feasibly be pulled into one processor with more options? For example I add CiviiCRM Contact 1 and map the default contact fields and custom fields. Below that there are checkboxes for me to enable and use/sync:

* Address
* Phone
* Note
* Email
* Link.URL
* Group
* Tag

When an option is selected it adds new fields to map for that contact, so it's all within one CiviCRM Contact Processor. 

I am unsure if it makes sense to have Activity & Relationship as part of that same processors, it seems like those may need to be their own.

**Comment by mecachisenros** [comment]
@danaskallman @christianwach  How about something like this: 
![contact-processor](https://cloud.githubusercontent.com/assets/3038096/18915811/1fe3fac8-858a-11e6-9435-0a89f13c67ed.gif)

**Comment by christianwach** [comment]
@mecachisenros Nice! It could be better still if the accordion sections only show up if you select the "Process x for this Contact" checkbox. Or have I misunderstood how this works?

**Comment by mecachisenros** [comment]
@christianwach Yes that is the idea, I haven't got that far yet.
Show/hide accordion based on checkboxes at the top, any feedback before I move forward is appreciated.

**Comment by christianwach** [comment]
@mecachisenros It looks fantastic! I can't wait to have a play.

**Comment by danaskallman** [comment]
@mecachisenros nice! 

I am not sure I am following the process. What does the checkbox do that is separate from selection options in the accordion?

**Comment by mecachisenros** [comment]
@danaskallman the checkboxes enable an entity for that particular Contact processor, the accordions will be hidden be default (except for Contact Standard/Custom fields) unless you tick the checkbox at the top, but is not actually behaving like that in the demo above

**Comment by danaskallman** [comment]
@mecachisenros great, that makes sense. Checkbox adds accordion to then select and use processor.

**Comment by danaskallman** [comment]
@mecachisenros curious on thoughts if Relationships should be it's own Processor. I am torn, since it's just 3 fields and can see it being part of the contact processor. But then it only can be used if 2 contact processors are in place. I ask since if there i 10 contacts there could be 9 relationship processors too and wondering if there is a way the consolidate that in some way. 

Activity is pretty clear that is should be it's own Processor, I think.

**Comment by danaskallman** [comment]
This 0.3 branch is looking great! Though I just tried master and it didn't show the same, it was merged, right? Does the 0.3 tag need to be applied to it? 

Question what if a form is requesting more than one phone, email or street address? Is there a way to say/ask how many phone numbers will be processed and then select number and that would provide the spaces needed. For example home and cell number or cell and work number. 

I guess the same with any type of data where I can have more than 1, like Website/IM.

**Comment by christianwach** [comment]
@danaskallman The master branch has had the 0.3 branch merged #18 so you should see the new processor format, though you'll have to update any pre-0.3 forms. You might also like to try the demo forms in #19 which should save some time in getting a form off the ground.

**Comment by danaskallman** [comment]
thanks @christianwach for some reason the pull wasn't working initially. I'll try get to #19 this week too.

**Comment by danaskallman** [comment]
Nothing that having the extra options in the contact processor to add phone numbers, email, address, etc. has made it possible to have less processors on more complex forms when all contact fields are required. And only need to use additional say phone or email processor is more than one phone number or email address field is in a form for a particular contact.
