### ISSUE TITLE
Counties field not populated

### ISSUE THREAD

**Issue by dmgeurts** [mecachisenros/caldera-forms-civicrm#188]
CiviCRM deals with counties (UK user here) a bit awkwardly. We have it working in CiviCRM now but in Caldera I can't get the County field (state/province) to populate, it remains empty.

I'm using the default CiviCRM Contact and Address form. The extra fields to custom entries are all working perfectly and the other address details also show up fine.

**Expected behavior**
Counties to be displayed in the form as they are in CiviCRM

**Comment by agileware-justin** [comment]
See my answer here, https://civicrm.stackexchange.com/questions/37901/cf-civicrm-state-province-field-dropdown-not-populating-after-country-is-chosen/37903#37903

**Comment by dmgeurts** [comment]
Perfect, wouldn't have thought of checking that. My assumption was that if left default all fields would be available. I did not have to set a default state/county, for which I'm grateful as that would have caused no end of complaints!
