### ISSUE TITLE
State Field

### ISSUE THREAD

**Issue by danaskallman** [mecachisenros/caldera-forms-civicrm#2]
The CiviCRM State field shows all states around the world after the country is selected. 

In CiviCRM currently, using profiles, the country is added before the state in profile forms so that when the country is selected the state field then only shows states from what country. Is that something that is going to be able to be done here?

**Comment by mecachisenros** [comment]
@danaskallman thanks for feedback, I'm aware of this, I'm currently looking at it, trying to figure out what would the best approach to link them so that the State/Province limits the options to the selected Country

**Comment by mecachisenros** [comment]
@danaskallman This issue should be fixed now via 6ec163b866e1e60259785947aa47db065d99345f and 789ed5bb8f135553bb8c8fdc05e08e6d79a4fe02

**Comment by danaskallman** [comment]
I was testing this today on setting up a form for a client website and when I selected country, the state shows just the word array multiple times. It does it on it's own too, without country field added. 

![carldera-civicrm-state-array](https://cloud.githubusercontent.com/assets/1139085/17105872/004964e8-5257-11e6-8d2b-e26c58b97842.png)

**Comment by danaskallman** [comment]
Just confirming that this is fixed, no longer shows array. Shows all states around the world if no country is selected, once country is selected it shows that states for that country.
