### ISSUE TITLE
Dedupe rule selection question 0.3 issue

### ISSUE THREAD

**Issue by danaskallman** [mecachisenros/caldera-forms-civicrm#20]
I am curious about how the dedupe rule selection in the form works. I am testing a form where I am using my name and email and it has now created 3 contacts. I am using the `Individual - Name and Email (reserved) - Surpervised` rule. Shouldn't that just update my existing contact details or add an activity to an existing contact?

**Comment by danaskallman** [comment]
@mecachisenros @christianwach I am getting duplicates a lot when submitting forms. Are you having the same issue? Is it best not to use dedupe option?

**Comment by christianwach** [comment]
@danaskallman I've not used dedupe rules with this plugin yet - hopefully @mecachisenros has a better idea of what's going on

**Comment by danaskallman** [comment]
I can add some sample forms, but it's basically any form I create is adding the contact as a new contact, and it's across all the sites I have this on too. Not matter if I am logged and using the pre-populate contact details option for the contact.

**Comment by danaskallman** [comment]
Just did a quick test on this commit https://github.com/mecachisenros/caldera-forms-civicrm/tree/6094bbfe22fa2315f6afa1fdc0c75519ead67ca4 and duplicates are not created at that point. So seems connected to 0.3 merge

**Comment by danaskallman** [comment]
Noting this is resolved by #22 in my tests, thanks @christianwach

**Comment by mikaweinstein** [comment]
I am having the same issue Dana initially had, where in any number of scenarios (including when I'm logged in), contacts entered via the integration are creating duplicates rather than following the dedupe rule. I am using 0.4, which pr #22 is merged into. Any ideas, or anyone else having this issue?
