### ISSUE TITLE
Participants status is Pending(incomplete Transaction) even though payment is recorded

### ISSUE THREAD

**Issue by KilakwaBT** [mecachisenros/caldera-forms-civicrm#202]
We have a registration form for an event where in some cases the participant ends up with the status 'Pending(Incomplete Transaction). The payment is recorded as complete with transaction ID in CiviCRM. It is also listed in the event registration with a balance due of $0.00. This does not happen with every transaction. Still working on variables that cause this behavior. I will update this issue as more information becomes available.

WordPress version: 5.6
CiviCRM Version: 5.33.2
Payment Processor: PayPal Express

**Comment by KilakwaBT** [comment]
I have some more details on this. Here are the particulars.

- All users must be logged in to access the form.
- We have the 'Populate User Data' Check box checked on the Contact 1 Which the registration and contributions is connected to.
- In many cases there are multiple contacts in Civi that have the same email so a new contact is created when the user creates an account.
- When the form is processed the contributions data goes in under the contact connected to the WordPress account (usually newly created)
- The event registration goes under an existing contact that matches the dedupe rule (First Name, Last Name & email) and is not connected to a WordPress account.
- The result is a registration that is 'pending from incomplete transaction' status since there is no contribution.

We are still watching these and will report any data as we have more information. If there are any questions or stuff we may want to looks at please let us know.

Thanks

**Comment by agileware-justin** [comment]
@KilakwaBT did you set up a Contribution processor?

**Comment by KilakwaBT** [comment]
The order processor is in place referencing the line item for the participant processor. The contributions are being recorded correctly.

**Comment by agileware-justin** [comment]
> The result is a registration that is 'pending from incomplete transaction' status since there is no contribution

"since there is no contribution" confused me. Maybe attach an export of the Caldera Form JSON so others can see how it is configured. Or screenshots.

**Comment by KilakwaBT** [comment]
Sorry just getting back to this. The original event ended and we are preparing for a new event.  Here are screen shots of the configuration.

![image](https://user-images.githubusercontent.com/28601657/117858715-286e8880-b25c-11eb-9a44-3db378e98bff.png)

![image](https://user-images.githubusercontent.com/28601657/117858775-37553b00-b25c-11eb-98e0-d615ec40f36a.png)

![image](https://user-images.githubusercontent.com/28601657/117858846-49cf7480-b25c-11eb-8e52-e7281d4d54ee.png)
![image](https://user-images.githubusercontent.com/28601657/117858969-6ff51480-b25c-11eb-9001-a72d8b9cc97b.png)

Results in Civi:

![image](https://user-images.githubusercontent.com/28601657/117859089-93b85a80-b25c-11eb-8271-413a1d9400ca.png)

I get similar results in a couple different sites. I nave updated the CF_CiviCRM plugin to the most recent dev version. If anyone can see if something is incorrect in the configuration please let me know.

Thanks for the help!

**Comment by kcristiano** [comment]
@KilakwaBT On the Order processor the Contribution Status should be set to Pending(default) 

![image](https://user-images.githubusercontent.com/1892544/117883135-0afbe780-b279-11eb-9470-b33af1954de9.png)

This change was needed after CiviCRM 5.20+

**Comment by KilakwaBT** [comment]
@kcristiano that did it in my test site. Thanks
