### ISSUE TITLE
Website field in Contact 0.3 adding multiple times

### ISSUE THREAD

**Issue by danaskallman** [mecachisenros/caldera-forms-civicrm#24]
When using the `Process website for this contact.` for contact processor in 0.3 the website gets added multiple times on multiple submissions. So for example the Main website or twitter website appear multiple time if the form is submitted more than once.

**Comment by mecachisenros** [comment]
@danaskallman this should be fixed via 728d8fc794cccc374c093201dbaa42ffae09828a

**Comment by mecachisenros** [comment]
@danaskallman I'll close this, feel free to reopen it if you still get this issue
