### ISSUE TITLE
Does Address Location Type need to be set?

### ISSUE THREAD

**Issue by seascoot** [mecachisenros/caldera-forms-civicrm#26]
While setting up contact processors I discovered that unless I explicitly set the "Address Location Type" in the Contact Address section the form fails to submit with an associated error:

`PHP Fatal error:  Uncaught CiviCRM_API3_Exception: [mandatory_missing: Mandatory key(s) missing from params array: location_type_id`

Is a value for the location type required in CiviCRM?

**Comment by mecachisenros** [comment]
@seascoot yes the Address Location Type is a required field in CiviCRM.

Thank you for reporting.

Also thank you for reminding me, the reason for not explicitly requiring it when setting up the Address entity in the Contact processor was to be able to expose the Address Location Type in the front end and let the user/form submitter chose the location type they want. So you can have a required dropdown field that autopopulates the Address Location Types from Civi, and then in the Address entity settings in the Contact processor you map that dropdown field. So this way you would have both options, set a specific Address Location Type or let the user chose one.

Does that makes sense?

I'm not sure right now why I haven't implemented it yet, I'll go through my notes and report back.
