### ISSUE TITLE
API file warnings

### ISSUE THREAD

**Issue by seascoot** [mecachisenros/caldera-forms-civicrm#27]
When a Caldera Forms Civicrm form I'm working on is opened I get a lot of "failed to open stream: No such file or directory" warnings originating from 
`WARNING: D:\wamp\www\mysitename\wp-content\plugins\civicrm\civicrm\CRM\Utils\File.php:387 - `

The following are reported:
fopen(api/v3/UFMatch/Getsingle.php): failed to open stream: 
fopen(api/v3/UFMatch/Getfields.php): failed to open stream: 
fopen(api/v3/Contact/Getsingle.php): failed to open stream: 
fopen(api/v3/Contact/Getfields.php): failed to open stream: 
fopen(api/v3/ContactType/Getfields.php): failed to open stream: 
fopen(api/v3/CustomGroup/Getfields.php): failed to open stream: 
fopen(api/v3/Address/Getsingle.php): failed to open stream: 
fopen(api/v3/Address/Getoptions.php): failed to open stream: 
fopen(api/v3/Phone/Getsingle.php): failed to open stream: 
fopen(api/v3/Phone/Getfields.php): failed to open stream: 
fopen(api/v3/Email/Getfields.php): failed to open stream:

**Comment by mecachisenros** [comment]
@seascoot That looks odd to me, it seems like it could be related to a WAMP path misconfiguration? What CiviCRM version are you on?

**Comment by seascoot** [comment]
WP is 4.6.1
Civi is 4.7.12
