### ISSUE TITLE
Group link works in separate processor but not in Contact processor

### ISSUE THREAD

**Issue by seascoot** [mecachisenros/caldera-forms-civicrm#28]
I found that if I tried to create a group relationship from the optional dropdown in a contact processor it caused a failure in the form to submit.  If, however, I create a separate group processor it seems to work fine and get carried over to Civi.

**Comment by mecachisenros** [comment]
@seascoot are you using the latest master branch of the plugin? It looks like what you are describing has been addressed already, see #21

**Comment by seascoot** [comment]
Updating to a more recent master branch version fixed the issue.
