### ISSUE TITLE
Checkbox submission error

### ISSUE THREAD

**Issue by danaskallman** [mecachisenros/caldera-forms-civicrm#29]
I am using a checkbox field, in both CiviCRM 4.7.14 and WP 4.7 and Caldera 1.4.6.1 I can choose one option in the checkbox but not multiple. So it submits file if I just select one, but get the following errors when I try to select more than one option in a checkbox field. 

~~~
Warning: array_keys() expects parameter 1 to be array, string given in /var/www/m4bl/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/BAO/CustomGroup.php on line 1509

Warning: implode(): Invalid arguments passed in /var/www/m4bl/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/BAO/CustomGroup.php on line 1511

Fatal error: Uncaught CiviCRM_API3_Exception: [2001: 'latin, indian, middle-eastern' is not a valid option for field custom_9 thrown in /var/www/m4bl/wordpress/wp-content/plugins/civicrm/civicrm/api/api.php on line 45
~~~

Thoughts?

**Comment by mecachisenros** [comment]
@danaskallman the referenced commit should fix the issue for the Contact processor, I'll make some more tests later this evening, as the Activity processor is probably affected as well.

**Comment by danaskallman** [comment]
@mecachisenros yeah, that worked. Thanks! I can test once the Activity processor too, just let me know.

**Comment by mecachisenros** [comment]
@danaskallman there's a new 0.4 branch which should address this issue for all processors via da9c590dcc617018352ed5cab5faa33b47cf7c32 and b07df17205451ba20445d3b20c7561e729e6e233

I'll close it for now, just reopen it if there's any regressions
