### ISSUE TITLE
Prepopulate default country and state from CiviCRM

### ISSUE THREAD

**Issue by danaskallman** [mecachisenros/caldera-forms-civicrm#3]
In the CiviCRM core localization settings there is a way to set default country and state, which is helpful when working with organizations that are state or city based. Is it possible that the state and country fields default to this if that setting is in place? Or an option to do so in the field setup?

Additionally, if that is setup, can state along be used without the country field?

**Comment by mecachisenros** [comment]
@danaskallman As requested, the Country and State/Province fields have now a default option which by default will have the Localization values form CiviCRM,
0b70618f153074e97fc5ae453de5d0220e3dfcf8

**Comment by danaskallman** [comment]
@mecachisenros thanks!

In my tests it worked for country but not for state. One thing I noted is that when Adding the State Element, after adding it, it did not close the caledara pop up to select element. It did close it for country. Not sure that would be why, but noting it in case.

**Comment by mecachisenros** [comment]
Thanks @danaskallman, my fault, the Country field worked because it was set in Civi's Localization settings, but the State was empty right? I assumed the default Localization settings would have been passed as an empty string if none present, but it wasn't the case, this should do it 198bfaff457ea67456dea0297158abe69324a2d0

**Comment by mecachisenros** [comment]
Nope, that fixes the javascript error but it looks like the **default State/Province field** is not available via Civi's API at least in v4.6.16, it does work in v4.7.9
I'll have a more deeper look tomorrow.

**Comment by danaskallman** [comment]
I see, interesting. The settings in the field to set default state is helpful.

**Comment by mecachisenros** [comment]
I could add a version check and retrieve the default State Localization value via `CRM_Core_DAO` to make it work with 4.6.x

Aside from that I just realized that in the same Localization page there's a **Available Country** and **Available States and Provinces** options, should the Countries/States in the form builder be limited to the these settings? Any thoughts?

**Comment by danaskallman** [comment]
@mecachisenros re:
>  should the Countries/States in the form builder be limited to the these settings? Any thoughts?

Yeah, this is a great idea. Only list countries and states that have been enabled. That list is quite long by default and can see users not being happy with that. Thanks for thinking of that one.

**Comment by mecachisenros** [comment]
Thanks @danaskallman, latest commit added should fix all mentioned above
> should the Countries/States in the form builder be limited to the these settings?
