### ISSUE TITLE
CiviCRM_API3 error Mandatory keys missing prams array: phone

### ISSUE THREAD

**Issue by danaskallman** [mecachisenros/caldera-forms-civicrm#30]
We have a form up and are getting this fatal erro

`Fatal error:  Uncaught CiviCRM_API3_Exception: [mandatory_missing: Mandatory key(s) missing from params array: phone\n\n  thrown in /var/www/m4bl/wordpress/wp-content/plugins/civicrm/civicrm/api/api.php on line 45\n'`

Some of the submissions in Caldera appear like this `(___)___-1___` and that's what gets passed onto Civi. 

Not 100% sure they are related, but maybe. Thoughts on why? Or if it's even a related issue.

It's Civi 4.7.14, WP 4.7 and Caldera 1.4.7

**Comment by mecachisenros** [comment]
@danaskallman that means the Phone field is empty when the form is submitted, the required fields for Civi's Phone API are the contact_id and the _phone_ field. 

That _1_ in the phone mask looks odd, can you double check the mask format? If you have it set to custom all digits must be indicated with a _'9'_, see the picture below, the _1_ after the hyphen is incorrect, it should be a _9_ (unless you explicitly want a 1 there :upside_down_face:)
![capture](https://cloud.githubusercontent.com/assets/3038096/21677970/925d5cb4-d334-11e6-982d-ad7a70997f50.PNG)
Also test changing the Field Type form _Phone Number_ to _Single Line Text_ ?
I think the mask in the Phone number field its a bit inconsistent (browser support?) and there's going to be improvements to it in CF v1.5

**Comment by danaskallman** [comment]
@mecachisenros I am actually using the Local option, but can change it. It is all showing (999)999-9999

The sample showed above was how some of the submissions are appearing in the admin.

I changed to text field and seems to work, maybe I'll leave that for now. Though phone numbers may be entered wrong that way.

**Comment by danaskallman** [comment]
Issue resolved by using the phone and address processors and not  options  within the contact processor. Also since those fields are not required, set condition to only process if fields are filled out.
