### ISSUE TITLE
File upload fields mapping

### ISSUE THREAD

**Issue by danaskallman** [mecachisenros/caldera-forms-civicrm#31]
I was attempting to map a file upload to a custom field and it doesn't seem to work. I created a custom field for an activity type using file upload option. When I had the field mapped the submission didn't work, if I removed it the form worked. Is this something that can't be done?

**Comment by DouglasMcLellan** [comment]
I second this. I need to be able to attach a document to a membership application. The option seems to be there in that I can map it but there is then an error message.

**Comment by mecachisenros** [comment]
@danaskallman @DouglasMcLellan this has been implemented in the [latest release](https://github.com/mecachisenros/caldera-forms-civicrm/releases).

The **File** and **Advanced File** fields have a **CiviCRM File Upload**  setting, tick this setting to map it to a Contact Custom field, Activity Custom field, Note, and Activity attachment.

For the Activity attachment you can use the Advanced File to allow multiple files upload, for the rest of Custom fields use the File field.
