### ISSUE TITLE
Activity Type Event Registration add Select Event 

### ISSUE THREAD

**Issue by danaskallman** [mecachisenros/caldera-forms-civicrm#32]
In the activity processor we can select Event Registration as an activity type. However, there is no way to connect that activity to an event. so someone submitting a form could be added as a participant, or multiple contacts/participants, to an specific event. I know in #25 there's a reference to paid events, however in this case I am imagining to be able to add participants to a free event, like:

-  for parents registering children, or 
- guests for a gala where a table was purchased

**Comment by squeezeboxer** [comment]
Was there any movement on this one? We’re hoping to get an events processor or workaround for our free events.

**Comment by mecachisenros** [comment]
@squeezeboxer a Participant processor (for free and paid events) has been developed in the [dev](https://github.com/mecachisenros/caldera-forms-civicrm/tree/dev) branch, I would suggest to test in test/staging environment first, and report here if you find any issues.

**Comment by kirk-circle** [comment]
Hi @mecachisenros, we too need a participant processor for free events. Is the code for this in the [dev](https://github.com/mecachisenros/caldera-forms-civicrm/tree/dev) branch, or is it in the [process-participants-order](https://github.com/mecachisenros/caldera-forms-civicrm/tree/process-participants-order) branch? Thanks.

**Comment by danaskallman** [comment]
This is merged into master, so am closing. We can re-open if needed.
