### ISSUE TITLE
Contact Type is removed not added on form submission

### ISSUE THREAD

**Issue by danaskallman** [mecachisenros/caldera-forms-civicrm#35]
When I submit a form that uses either just the parent contact type like Individual, or a say Volunteer, or Student, it seems to remove any previous contact type that may have been associated with my contact record already. Is there a way the contact type can be help and added, so I can be multiple contact types, when a form is submitted?

**Comment by mecachisenros** [comment]
@danaskallman this should be fixed in 0.4 branch, feel free to reopen if it's not
