### ISSUE TITLE
Installation instructions / getting started

### ISSUE THREAD

**Issue by richardsplayground** [mecachisenros/caldera-forms-civicrm#37]
Sorry for the newbie question - I'm new to caldera forms.  Would it be possible to provide a brief getting started guide for how to get this caldera-forms-civicrm to work with a basic install of the caldera forms plugin?

Thanks so much.

**Comment by danaskallman** [comment]
@richardsplayground I am working on some documentation, should have something to share in the next couple of weeks. 

By adding this plugin, there are new processors available to get data into CiviCRM. But there's quite a few things that can be done, so the documentation should cover that.

**Comment by mecachisenros** [comment]
thank you very much @danaskallman can't wait to see it! 

@richardsplayground a very brief description would be that this plugin/integration, as @danaskallman mentions, adds a few processors for CiviCRM entities which allows you to _map_ form fields to CiviCRM fields/entities.

If you are new to Caldera Forms, the plugin authors have a start guide [here].(https://calderaforms.com/getting-started/)

**Comment by danaskallman** [comment]
Initial docs published here https://github.com/mecachisenros/caldera-forms-civicrm/tree/0.4/docs

I think we can close this and continue adding edits/improvements moving forward.

**Comment by gzh1960** [comment]
== Installation ==

1. Extract the plugin archive
1. Upload plugin files to your `/wp-content/plugins/` directory
1. Activate the plugin through the 'Plugins' menu in WordPress
