### ISSUE TITLE
Civi Country & State in notification emails

### ISSUE THREAD

**Issue by loneprairie** [mecachisenros/caldera-forms-civicrm#41]
Great plugin - successfully creates a Civi contact, assigns group, adds activity as expected. Thank you for building and sharing.

In notification email to staff and autoresponder to form user, country and state are returned as (I assume) their Civi ID# - please see attachments.

![country_caldera](https://cloud.githubusercontent.com/assets/11682835/26016347/3b50a4d0-372a-11e7-8342-cf642ab16a13.png)

![state_caldera](https://cloud.githubusercontent.com/assets/11682835/26016358/4295e7dc-372a-11e7-9dad-53339c3d2df0.png)

Not such a big deal for staff but user might find it odd.

**Comment by mecachisenros** [comment]
@loneprairie glad you find the plugin useful and thank you for the feedback.

I'll have a look at this and get it sorted.

**Comment by mecachisenros** [comment]
this should be fixed via 5c6a466c0d399a0738e055092e368b6b5529d2c1
