### ISSUE TITLE
Contact Autocomplete Select Field

### ISSUE THREAD

**Issue by danaskallman** [mecachisenros/caldera-forms-civicrm#43]
In custom fields in CiviCRM we can create a Contact Reference field type that uses the Autocomplete-Select field type. Can this be a custom field type used in Caldera forms too? How complex would it be to implement?

**Comment by mecachisenros** [comment]
hi @danaskallman sorry for the late reply.
I'll get back to you with this by the end of the week, hopefully with it done :crossed_fingers:

**Comment by laryn** [comment]
+1 This would be great. I'm trying to do this in a work around for the moment but having issues that I'll post in another ticket.

**Comment by kcristiano** [comment]
@mecachisenros This relates to the functionality I reviewed with you last week.   Let me know what needs to be done to make this happen.

**Comment by danaskallman** [comment]
Note: The auto-complete in this case is tied the the default Organization field, so it's the `Current Employer` field that is tied to an Individual contact type that then also adds the Employee/Employer relationship.

**Comment by danaskallman** [comment]
This is now in 0.4.4, now merged into master. So closing issue
