### ISSUE TITLE
Map to membership

### ISSUE THREAD

**Issue by DouglasMcLellan** [mecachisenros/caldera-forms-civicrm#44]
Hello

Is it possible to have a processor than can map a membership type (e.g. Full Member, Associate Member, Affiliate)?

Or am I missing something?

Thanks

**Comment by agileware** [comment]
I don't think Memberships have been implemented yet at all. There is no Contributions integration. See #25

**Comment by agileware** [comment]
Thanks @mecachisenros

**Comment by Dubidubiduu** [comment]
So it's still not possible to add members through caldera form plugin, right?

**Comment by mecachisenros** [comment]
@Dubidubiduu not at the moment.

**Comment by jusfreeman** [comment]
We've stopped work because @mecachisenros has done this already, https://github.com/mecachisenros/caldera-forms-civicrm/tree/0.4.4/processors/membership

Thanks @mecachisenros - can you close this issue as fixed?

**Comment by mecachisenros** [comment]
@jusfreeman will close this with the next release (0.4.4) there are still a couple of things to polish.

**Comment by mecachisenros** [comment]
Memberships are now supported in version 0.4.4.
