### ISSUE TITLE
Is there a limit to the number of custom fields?

### ISSUE THREAD

**Issue by KilakwaBT** [mecachisenros/caldera-forms-civicrm#47]
I am building a large form with may custom fields. All is working well except a couple of the custom fields are not showing in the processor. I added a new one and it didn't show up. Is there is a limit to the number the processor will handle. I have over 25 custom fields to process.

Let me know.

Thanks!

**Comment by KilakwaBT** [comment]
Just tried adding a new custom field group in Civi and those fields show up in the processor. Any thoughts? I can reorganize my custom field groups if there is a limitation to the number of fields in the group.

Thanks

**Comment by mecachisenros** [comment]
@KilakwaBT thank you for reporting. There _was a limit_ of custom fields, if you have more than 25 Custom Groups sets or more than 25 Custom Fields per set that's probably why, the referenced commit should fix it. Just do a `git pull` against the master branch. 

Another reason might be if you are trying to add a Custom Field that extends an entity that is not a **Contact, Individual, Household, Organization or Custom Contact Type**, like for example a Participant custom field, those won't show up in the Contact processor. Also the custom fields are filtered (show/hide) based on the Contact Type and Contact Sub Type dropdowns at the top of the processor settings, meaning that based on the Contact Type and Contact Sub Type selection you will only see relevant custom fields for that particular Contact Type, if that makes sense.

Let me know if the referenced commit fixes the issue.

**Comment by mecachisenros** [comment]
@KilakwaBT this should be fixed, I've pushed a [new release](https://github.com/mecachisenros/caldera-forms-civicrm/releases), if you still have this issues feel free to reopen it.
