### ISSUE TITLE
Bleeding edge alpha?

### ISSUE THREAD

**Issue by cdhassell** [mecachisenros/caldera-forms-civicrm#48]
The README says the code is bleeding edge alpha stage.  Is that still true or is that comment a leftover from when it was first posted?

**Comment by mecachisenros** [comment]
@cdhassell I think a _Stable Beta_ would be more appropriate at this point, the plugin is being used in a few sites and the bugs that pop up I try to fix them as soon as possible.

**Comment by mecachisenros** [comment]
@cdhassell I've changed the readme
