### ISSUE TITLE
Map to Employer

### ISSUE THREAD

**Issue by elizolivares** [mecachisenros/caldera-forms-civicrm#49]
Is it possible to have a select list field on a contact form that maps the individual contact to their employer? So a form with something like 'first_name', 'last_name', 'email', and 'employer_name', where the individual -> employer/organization relationship is created?

**Comment by mecachisenros** [comment]
@elizolivares you can create a select field (or a text field) with predefined Companies/Organizations and map that field to the Individual's _Current Employer_ field, Civi will create the relationship when the Individual is created or updated.

Alternatively you can use two Contact processors, one for the Individual and another one for the Organization, then add a Relationship processor where you can set the type of relationship you want.

**Comment by elizolivares** [comment]
Aha! That first one worked out just fine in my testing. Thanks so much, this is a fantastic plugin!

**Comment by mecachisenros** [comment]
@elizolivares glad you like it and find it useful, if you find any bugs or have any questions/requests feel free to open another issue.

I'll close this now.
