### ISSUE TITLE
Auto populate contact data causes bad page load for logged in user

### ISSUE THREAD

**Issue by seascoot** [mecachisenros/caldera-forms-civicrm#52]
I'm using Woocommerce with a caldera-forms-civicrm form shortcode inside a custom product tab.  If Auto populate contact data is enabled for Contact 1 (only on that contact - not enabled elsewhere) the page displays fine for a non-logged in user.  If I log in as a non-admin user the page no longer loads properly:

- no product image
- no gallery images
- "Decription" and "Additional information" tabs work but the tab containing the form and 3 tabs after it displays but have broken links

Errors in the console show:
Uncaught ReferenceError: jQuery is not defined
    at (index):13
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
2comodosslseal.js:2 A Parser-blocking, cross site (i.e. different eTLD+1) script, https://secure.comodo.com/trustlogo/javascript/trustlogo.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message.See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ comodosslseal.js:2
****edited out url*****/#tab-seller_info Failed to load resource: the server responded with a status of 500 ()

Oddly, if I try this as admin logged into the WP dashboard the page loads OK.

This used to work about 5 months ago when it was last used. I have since gone through several WP, Woocommerce, Caldera, and master updates so I'm not sure at which point it got broken.

I have been using a non-standard theme - Generatepress.  However, switching to Storefront theme gives the same result.

**Comment by mecachisenros** [comment]
Can you export the form in question and upload it here?
I'll try to reproduce this.

**Comment by mecachisenros** [comment]
@seascoot can you test with the [latest release](https://github.com/mecachisenros/caldera-forms-civicrm/releases) and report back, there was an issue with the autopopulate option.
