### ISSUE TITLE
Second contact not loading

### ISSUE THREAD

**Issue by laryn** [mecachisenros/caldera-forms-civicrm#54]
I need to have the Contact 1 (Individual) be able to select their employer (Contact 2 - Organization) from a predetermined list, rather than just typing, to reduce duplicates. Ideally this could be an [Autocomplete select based on a CiviCRM group](https://github.com/mecachisenros/caldera-forms-civicrm/issues/43), but in the meantime I'm trying to set the Employer up as a basic select dropdown. I exported Org names from CiviCRM and imported them as the select options, and chose a dedupe rule for the processor that only needs to match the Org name. Then I have a relationship processor set up to connect Contact 1 and Contact 2.

It seems this should work, however when I select an Org from the dropdown and submit, I get this:

```
Fatal error: Uncaught CiviCRM_API3_Exception: [undefined: Expected one Contact but
 found 0 thrown in /path/wp-content/plugins/civicrm/civicrm/api/api.php on line 45
```
If I turn off the Contact 2 and Relationship processors I can submit fine.

Any ideas?

**Comment by laryn** [comment]
Actually, I just realized in this case I can take advantage of the fact that "Current Employer" is a field on the Individual, so I don't need the second two processors!

The error still holds for anyone trying to do this with any other relationship besides employer, however.

**Comment by laryn** [comment]
Update: Even using the 'Current Employer' field doesn't seem to use the dedupe rule I specified so I'm still ending up with duplicates.

**Comment by mecachisenros** [comment]
@laryn I'll investigate this, but if you are on CiviCRM v4.7.24 I believe the referenced commit is related to this issue.

**Comment by mecachisenros** [comment]
@laryn any updates on this? I've just pushed a new release, if you test it please report back.

Re _Contact Autocomplete based on groups_, this will be soon available.

**Comment by laryn** [comment]
@mecachisenros Thanks -- I'll test and report back!

**Comment by laryn** [comment]
@mecachisenros The relationships issue seems to be solved in the latest release. Thanks!

The Contact autocomplete (based on a group) functionality will be great to reduce redundancy and inconsistency over time, but this is a great start for what we need.
