### ISSUE TITLE
Can't edit any Caldera Forms error message: One of parameters (value: ) is not of the type Integer

### ISSUE THREAD

**Issue by danaskallman** [mecachisenros/caldera-forms-civicrm#6]
When I go to Edit a form it says this:

> Sorry but we are not able to provide this at the moment.
> One of parameters (value: ) is not of the type Integer
> 
> Return to home page.
> 

And backtrace shows this:

~~~
#0 /public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(360): CRM_Core_Error::backtrace()
#1 /public_html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Type.php(415): CRM_Core_Error::fatal("One of parameters  (value: ) is not of the type Integer")
#2 /public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/DAO.php(1251): CRM_Utils_Type::validate(NULL, "Integer")
#3 /public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/DAO.php(1168): CRM_Core_DAO::composeQuery("\nSELECT  v.label as label ,v.value as value, v.grouping as grouping\nFROM   ...", (Array:1), TRUE)
#4 /public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/OptionGroup.php(248): CRM_Core_DAO::executeQuery("\nSELECT  v.label as label ,v.value as value, v.grouping as grouping\nFROM   ...", (Array:1))
#5 /public_html/wp-content/plugins/caldera-forms-civicrm/includes/functions.php(1081): CRM_Core_OptionGroup::valuesByID(NULL)
#6 [internal function](): cf_civicrm_custom_fields_options_presets((Array:4))
#7 /public_html/wp-includes/plugin.php(235): call_user_func_array("cf_civicrm_custom_fields_options_presets", (Array:1))
#8 /public_html/wp-content/plugins/caldera-forms/ui/edit.php(270): apply_filters("caldera_forms_field_option_presets", (Array:0), (Array:21))
#9 /public_html/wp-content/plugins/caldera-forms/classes/admin.php(1286): include("/public_html/wp-content/plugins/caldera-forms/ui/edit.php")
#10 [internal function](): Caldera_Forms_Admin->render_admin("")
#11 /public_html/wp-includes/plugin.php(525): call_user_func_array((Array:2), (Array:1))
#12 /public_html/wp-admin/admin.php(236): do_action("toplevel_page_caldera-forms")
#13 {main}
~~~

@mecachisenros is there a quick fix for this?

**Comment by mecachisenros** [comment]
@danaskallman it looks like is not related to the latest commit but rather to a Options custom field (ie, dropdown, select, checkbox, radio etc) I might be wrong, but have you recently added a custom field of the mentioned type? Also which Civi version are you using?

You can revert back downloading downloading/cloning from here https://github.com/mecachisenros/caldera-forms-civicrm/tree/487e5a623267110a16bcfb9e99cf989c8ff9676a

**Comment by danaskallman** [comment]
That seems accurate, I reverted to this https://github.com/mecachisenros/caldera-forms-civicrm/tree/9b993f2dd6e007261b304a96bbc213b9bcad7804 and was able to get back into editing the form. 

I'm using Civi 4.6 on all site at the moment. 

In both the cases I am testing the updates it is forms created prior to Options custom fields , I'll test on a new site tomorrow to confirm. Are there changes I need to make on existing forms before updating?

**Comment by danaskallman** [comment]
It actually happened on another site where the only form I have is for newsletter subscribers, so no integer related fields at all, just name and email. But also, a form created prior to the update referenced prior.

**Comment by mecachisenros** [comment]
@danaskallman  I'm trying to replicate this, I've created a clean build to double check but I can't reproduce the error you are getting, can you test with the referenced commit and report back?

**Comment by danaskallman** [comment]
@mecachisenros interesting. I was getting the same error/backtrace on all commits after the one I referenced worked. 

However, I just pulled in the latest commit and that works, so seems to resolve the issue?

**Comment by mecachisenros** [comment]
So latest commit 947ac7f9b7502ecd82c9c7fd7c4e043d9af89e28 resolved it then?

It's odd, as issue #4 and its commit ac069bbdbcb598c7e5e7571cd80539c26801e450 has nothing to do with the error/backtrace you are getting and I cannot see the connection between them, I tried to replicate it adding all custom fields of type select, checkbox, radio etc that Civi supports, even deprecated ones, but nothing.

947ac7f9b7502ecd82c9c7fd7c4e043d9af89e28 just ensures that the custom field has an `option_group_id` and casts the value passed to get the label/values as an integer, so the only circumstance that I can think of is if there was a custom field with empty options ie label/values.

**Comment by danaskallman** [comment]
I see. But why would it affect all caldera forms, even ones with no CiviCRM processors? I even created a new form and it wouldn't let me continued editing it. 

I'll continue reviewing and seeing if I can find any other reasons this issue would arise.

**Comment by mecachisenros** [comment]
The `Autopopulate` an `Bulk insert/presets` feature runs through a filter hook, so it doesn't matter if the form has a Civi processor or not, if there are Custom Options fields in Civi, these will show up in the CF field settings.
