### ISSUE TITLE
Question - How to Upload a Contact Image

### ISSUE THREAD

**Issue by sudama108** [mecachisenros/caldera-forms-civicrm#76]
We are capturing contacts in our congregation using Caldera Forms for CiviCRM. We have a field to upload a photo of the contact, so that it gets saved as a "Contact Image" in CiviCRM and when you view the contact in CiviCRM, the contacts photo shows up.

How do we do this with Calderia Forms?

**Comment by mecachisenros** [comment]
@sudama108 is the 'Contact image' field a custom field?

**Comment by sudama108** [comment]
No, Contact image is available as default field in CiviCRM. Within CiviCRM, you have this option available when creating a new contact or editing an existing contact.

**Comment by mecachisenros** [comment]
@sudama108 this feature is implemented in the master branch through this commit 057102fafa9b4a33b3341d54236ea7065cb05bf8.

The Image Url field is now exposed in the Contact processor, to use it add a File field to your form, enable the **CiviCRM File Upload** setting on the field, and then map the File field to the Image Url in the Contact processor.
