### ISSUE TITLE
Notice: Undefined variable: transient in ../includes/class-civicrm-caldera-forms-forms.php on line 157

### ISSUE THREAD

**Issue by sudama108** [mecachisenros/caldera-forms-civicrm#78]
Hi,

I get the following error when my form is loaded, after upgrading to v 0.4.4

Notice: Undefined variable: transient in .../wp-content/plugins/caldera-forms-civicrm-master/includes/class-civicrm-caldera-forms-forms.php on line 157

When I submit the form, I see these errors:

Notice: Undefined variable: transient in .../wp-content/plugins/caldera-forms-civicrm-master/includes/class-civicrm-caldera-forms-forms.php on line 157

Strict Standards: Only variables should be passed by reference in .../wp-content/plugins/caldera-forms-civicrm-master/processors/contact/class-contact-processor.php on line 152
Notice: Undefined index: phone_type_id in .../wp-content/plugins/caldera-forms-civicrm-master/processors/contact/class-contact-processor.php on line 369
Notice: Undefined variable: transient in .../wp-content/plugins/caldera-forms-civicrm-master/includes/class-civicrm-caldera-forms-forms.php on line 157

The form submits successfully though. What could be the cause of these error?

**Comment by mecachisenros** [comment]
@sudama108 those notices should be fixed in latest master branch.
