### ISSUE TITLE
When using a CiviCRM Priceset as the Source for a field, use the same localisation, currency format and if tax is enabled, use the tax display format

### ISSUE THREAD

**Issue by jusfreeman** [mecachisenros/caldera-forms-civicrm#79]
When using a CiviCRM Priceset as the Source for a field, use the same localisation, currency format and if tax is enabled, use the tax display format. These are defined in CiviCRM Localisation and CiviContribute, Component Settings.

For an Australian, localised CiviCRM. Currently, when using a Priceset as the source the values will be output like:
Membership Level 1 - 100

100 is missing the currency symbol and has no tax inclusive/exclusive text.

However, in CiviCRM the Priceset option is displayed like:
Membership Level 1 - $100 ex. GST

It would be ideal if the amount could be displayed on the Caldera Form using the same format as defined in CiviCRM.

We're willing to work on this one and submit a PR. Interested to hear your thoughts about this and any tips for implementation or other feedback.

<img width="523" alt="caldera-example" src="https://user-images.githubusercontent.com/10555210/47938202-670e8400-df37-11e8-8c56-28e93c8e9ed1.png">

<img width="1106" alt="caldera_forms_admin" src="https://user-images.githubusercontent.com/10555210/47938258-9624f580-df37-11e8-8748-f26c6f7902fa.png">

![civicontribute](https://user-images.githubusercontent.com/10555210/47938191-5e1db280-df37-11e8-81c4-8c92bece19b9.png)

<img width="891" alt="settings_-_localisation" src="https://user-images.githubusercontent.com/10555210/47938208-6ece2880-df37-11e8-916a-2883b2e7059a.png">

Agileware Ref: CFC-7

**Comment by mecachisenros** [comment]
@jusfreeman thanks for the detailed explanation, agreed on the tax, I'll have a look and implement it.

The currency was on my todo list ,see [here](https://github.com/mecachisenros/caldera-forms-civicrm/blob/master/fields/presets/class-civicrm-price-sets-presets.php#L124), my view is that currency should be:
1. optional (be able to enable/disable in the field setting, as I've seen price fields with the currency set in the Label)
2. if enabled use site's default currency setting
3. if Order or Contribution processor are present on the form, it should override site's default currency

I'll get this sorted.

**Comment by mecachisenros** [comment]
@jusfreeman the initial work on this issue is in the `dev` branch, mainly this commit 39236b656ce7c25adde642862fe8870f82a34491 any testing/feedback is appreciated.

**Comment by jusfreeman** [comment]
@mecachisenros legend mate! We'll take a look. Thanks very much.

**Comment by jusfreeman** [comment]
@mecachisenros we've tested these changes and they work as expected:

1. Display of $AUD and Australian GST (tax) is now correct
2. Payments are correctly recorded as CiviCRM Contributions with the correct amount.

Thumbs up from Agileware 👍

**Comment by jusfreeman** [comment]
Closing as this appears to be working now in the latest release.
