### ISSUE TITLE
Tax calculated twice

### ISSUE THREAD

**Issue by agileware-dat** [mecachisenros/caldera-forms-civicrm#87]
Hello,

Bug is found. In the contribution record, the price is taxed one more time.

Reproduce bug:

1. Set membership types with prices, for example "Member retired": $54.55 (this price excludes 10% GST)"

2. Create a price set for membership.

3. Add financial account named GST , choose "is tax" and tax rate is 10

4. Assign GST to member Dues types in Financial Types

5. Create a Caldera Form to register for membership.

6. Auto populate membership price to a dropdown field.

7. Add total amount as a calculate total amount value for payment process

5. Add Membership, Line-item and order processor.

6. Register a new member for "Member retired" 

The price should be $60 as it is inclusive GST value, but it was $66. So the price was taxed one more time.

The original value
![before_tax_value](https://user-images.githubusercontent.com/44013125/48928564-86943d80-ef34-11e8-9368-e0b7c5816486.png)

Calculate tax the second time
![tax is calculated again](https://user-images.githubusercontent.com/44013125/48928577-a0358500-ef34-11e8-8651-4480d2b5bf01.png)

Agileware Ref: CFC-15

**Comment by mecachisenros** [comment]
@agileware-dat thanks for reporting, I'll investigate and get back to you.

**Comment by agileware-fj** [comment]
@mecachisenros Just letting you know that I've assigned someone on our team to create a PR to fix this.

**Comment by mecachisenros** [comment]
@agileware-fj my findings so far about this, `Order.create` checks if the LineItems total amount match with the Contribution total amount [here](https://github.com/civicrm/civicrm-core/blob/master/CRM/Contribute/BAO/Contribution.php#L4976), that function doesn't take into account `tax_amounts` so you will always get a '_Line item total doesn't match with total amount._' error.

My work around has been to add the `tax_amount` + `line_total` [here](https://github.com/mecachisenros/caldera-forms-civicrm/blob/tax-fixes/processors/line-item/class-line-item-processor.php#L299) as I couldn't find any documentation or spec on the matter, but that seems to create the undesired effect described here.

Any input is appreciated.

**Comment by agileware-fj** [comment]
@mecachisenros Per #91 testing – On 5.9.1, if I comment out the line that adds the tax amount with the tax-fixes branch checked out, it records Contribution with correct amounts.

If I leave it in there, it fails with "Line item total doesn't match with total amount" error.

**Comment by mecachisenros** [comment]
@agileware-fj got it, I removed the `tax_amount` in the Line Item processor, it was failing for me because I've forgot to flush price set cache.

This should be fixed now on the `dev` branch.

**Comment by mecachisenros** [comment]
Fixed via 616a97d23fce940716334068835ee997d314a4c4.

**Comment by agileware-fj** [comment]
Thanks @mecachisenros, I can confirm that's working.

**Comment by agileware-dat** [comment]
Hi
I tested on dev 1.0.1 and it is working. I will close this issue.
Thanks
