### ISSUE TITLE
Map to Image URL field

### ISSUE THREAD

**Issue by KilakwaBT** [mecachisenros/caldera-forms-civicrm#88]
I am setting up a form for updating member directory information this includes an image. Currently the images are stored in CiviCRM's Image URL field. When mapping the fields in the CiviCRM contact processor I don't see the option to map to this field. 

Am I missing it or is it not an option? I could move the data to a custom field if that's the best way to go.

Let me know.

Thanks

**Comment by danaskallman** [comment]
hey @KilakwaBT see #64

**Comment by KilakwaBT** [comment]
@danaskallman I found it thanks! Got it working now!!

**Comment by mecachisenros** [comment]
@KilakwaBT that was added recently (perhaps you need to do a git pull/download latest release [0.4.5](https://github.com/mecachisenros/caldera-forms-civicrm/releases/tag/0.4.5) ), see #76 and this screenshot:
![image_url](https://user-images.githubusercontent.com/3038096/49113886-95f5ec80-f28e-11e8-8162-ec35aeba4cdf.jpg)

**Comment by KilakwaBT** [comment]
@mecachisenros Thanks, I found it and updated the plugin. All is good now! Thanks for all your work on this!!
