### ISSUE TITLE
New Custom Field Group, New Custom Fields and New Field Values NOT showing up in Caldera Processors for CiviCRM

### ISSUE THREAD

**Issue by lordofthegithub** [mecachisenros/caldera-forms-civicrm#89]
It appears that at the time the Plugin is installed, the Processors pull a Snap Shot of the Fields & Values, from CiviCRM.

Any subsequent changes in CiviCRM do not get reflected in the Processors or in the Caldera Layout Designer.

For example if you add 
1.  New Custom Field Group
2. New Custom Field
3. New Values to custom field
4. Add new Tag values to existing Tags

These do not reflect in the Processors and you are not able to map these fields for Auto Select in case of a DropDown menu functionality.

Happy to demonstrate if the developer would like to replicate the issue.

**Comment by mecachisenros** [comment]
@lordofthegithub I'm not able to reproduce the issue, do you happen to use any type of cache system that might be causing this?

**Comment by danaskallman** [comment]
@lordofthegithub I also close & reopen a Caldera form I'm working on if I make changes in Civi, that tends to then display any new data added.

**Comment by lordofthegithub** [comment]
> @lordofthegithub I'm not able to reproduce the issue, do you happen to use any type of cache system that might be causing this?

Good point @mecachisenros --- I am going to verify the caching plugins; those could be the culprits.

> @lordofthegithub I'm not able to reproduce the issue, do you happen to use any type of cache system that might be causing this?

@mecachisenros  thanks for a quick reply. There was a cache plugin W3, activated but the functionality was NOT enabled. That couldnt have been the suspect. To weed out the doubts, deleted a TAG and recreated the TAG; to see if the WP-CiviCRM plugin would pull the new tag after the W3 plugin was deleted, but still the same issue. Happy to get offline and demonstrate the issue.

@danaskallman thanks for checking on your end!
