### ISSUE TITLE
Auto Populate Select tag doesn't get cleaned up after deleting 

### ISSUE THREAD

**Issue by Dubidubiduu** [mecachisenros/caldera-forms-civicrm#92]
I'm in heavy testing Caldera forms for membership. After added a few Price shemes and Contribution pages the option autopopulate got a little bit messed up, so I tried to tidy up through deleting contribution pages and price shemes. But even after "Flush price sets cache" there are these old entries. (I don't believe I had that much, maybe the duplicates are already a caching prob)

Caldera 1.7.4
Caldera Forms CiviCrm 0.4.4
WP 4.9

![selectautopopulate](https://user-images.githubusercontent.com/34820982/50303715-399d7b80-048e-11e9-8e05-34988556129d.png)

**Comment by mecachisenros** [comment]
@Dubidubiduu does the issue persist?
