### ISSUE TITLE
Mandatory key(s) missing from params array: group_id, contact_id

### ISSUE THREAD

**Issue by lordofthegithub** [mecachisenros/caldera-forms-civicrm#96]
Hi CiviCRM/CalderaForms community,

I am seeing this error... and surprisingly I don't have these fields in my Caldera Form that interacts with CiviCRM using the CFC plugin developed by @mecachisenros. So I am wondering what could be the root cause. Thoughts @danaskallman @xHeliotrope @agilewarealok 

### Mandatory key(s) missing from params array: group_id, contact_id

#0 /home/DOMAIN.COM/wp-content/plugins/caldera-forms-civicrm-master_bak/processors/group/class-group-processor.php(92): civicrm_api3('GroupContact', 'create', Array)
#1 /home/DOMAIN.COM/wp-content/plugins/caldera-forms/classes/core.php(3139): CiviCRM_Caldera_Forms_Group_Processor->pre_processor(Array, Array, '_cf_process_5c4...')
#2 /home/DOMAIN.COM/wp-content/plugins/caldera-forms/classes/core.php(5029): Caldera_Forms::process_submission()
#3 /home/DOMAIN.COM/wp-content/plugins/caldera-forms/classes/core.php(3683): Caldera_Forms::process_form_via_post()
#4 /home/DOMAIN.COM/wp-includes/class-wp-hook.php(286): Caldera_Forms->cf_init_system('')
#5 /home/DOMAIN.COM/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /home/DOMAIN.COM/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#7 /home/DOMAIN.COM/wp-settings.php(488): do_action('wp_loaded')
#8 /home/DOMAIN.COM/wp-config.php(94): require_once('/home/SubDir/...')
#9 /home/DOMAIN.COM/wp-load.php(37): require_once('/home/SubDir/...')
#10 /home/DOMAIN.COM/wp-blog-header.php(13): require_once('/home/SubDir/...')
#11 /home/DOMAIN.COM/index.php(17): require('/home/SubDir/...')
#12 {main}

**Comment by lordofthegithub** [comment]
Hi All,

I have found this thread : https://github.com/mecachisenros/caldera-forms-civicrm/issues/58 
that I am going to follow to address the current issue #96.

However, I still haven't achieved a breakthrough in this https://github.com/mecachisenros/caldera-forms-civicrm/issues/94 regarding the processors; which apparently seems to be an environment/theme issue as per kind guidance of @mecachisenros .

**Comment by mecachisenros** [comment]
@lordofthegithub The error suggests that no _group_ (CiviCRM group) has been configured for the Group processor, or the Contact link is set to a Contact processor that is not present on the form, which makes sense if you are not able to view the Processor settings in #94

**Comment by lordofthegithub** [comment]
Thanks @mecachisenros. I've tried deactivating the plugins and still no luck. I need experienced pair of eyes to take a look at it. Sent you credentials and an email as well. Hopefully you can find my number from the emails that I've sent you and call back. Thanks again for a great plugin. Best. @lordofthegithub

**Comment by lordofthegithub** [comment]
@mecachisenros Thank you for your help. This issue is now resolved.

**Comment by lyonsdigital** [comment]
Similar issue here: Mandatory key(s) missing from params array: one of (first_name, last_name, email, display_name)

I'm not using a display_name and I don't see anywhere in the processor where I'd map it.
